### ISSUE TITLE
Removing an image raises an exception

### ISSUE THREAD

**Issue by molaschi** [cloudinary/cloudinary_sfcc_pagedesigner#12]
Step to reproduce:
- add a cloudinary image component to a page
- select an image and save
- refresh the page
- edit the page
- edit the cloudinary image component
- remove the image using the trash icon
An exception is raised in the browser:
```
ERROR TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at https://xxxx.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.static/Sites-Site/-/default/application/page-designer/vendor.7d7c0d7172a76b8f99d0.js:1:1507061
```
It seems that the exception is rasied when the `event sfcc:value` is emitted with the `payload` set to `null`. Setting the payload to an empty object `payload: {}` does not raise the exception anymore, and the value for the attribute is not removed but saved as the empty object itself.

**Comment by molaschi** [comment]
Yes i saw it... Is there any workaround? i.e. setting value to a predefined constant value like "empty", "null" (<- string)

**Comment by d-mendoza** [comment]
@molaschi 

The workaround would be to do the following:

- Delete the Cloudinary component from the page
- Insert a new Cloudinary component and choose the required image

You can still do other actions on the component, just can’t _edit and replace_ or _remove_ the previously selected image itself.

**Comment by dannyv-cloudinary** [comment]
Hey @Wepz.

Unfortunately as of yet there is no long-term fix, however @d-mendoza has provided a workaround above that may help.
