### ISSUE TITLE
Named and custom transformation choices aren't remembers when I edit an image.

### ISSUE THREAD

**Issue by amezick** [cloudinary/cloudinary_sfcc_pagedesigner#14]
1. edit an asset
2. add a image to an asset
3. select "transform" and select some transformations
4. save the change
5. edit the image again
6. select "transform" 
7. Notice that your transformations are missing.

The same goes for named transformations.
If I pick a named transformation and then go back and edit the image again, the transformation is not selected.  There is no other way to view the chosen transformations other than viewing the page source.

**Comment by naveenpras** [comment]
Transformations are remembered when reopening the Media library
