### ISSUE TITLE
Link Builder uses site name instead of site ID

### ISSUE THREAD

**Issue by d-mendoza** [cloudinary/cloudinary_sfcc_pagedesigner#26]
Steps to reproduce:

- Go to any Cloudinary Image Component 
- Click on Image Link (opens Link Builder)
- Select categories
- Add the image via the plus icon

The result is that it uses the sites name but it should use the ID instead.
https://github.com/cloudinary/cloudinary_sfcc_pagedesigner/blob/cdb9a0ef648044385fc4f154b94bd066f8bab009/cartridges/int_cloudinary_pd/cartridge/controllers/Links.js#L13

**Comment by d-mendoza** [comment]
I was trying to create the PR myself but for some reason I am getting this error, so not sure how to resolve exactly.

```
git push --set-upstream origin "Link builder should use site ID instead of site name when generating links"
fatal: invalid refspec 'Link builder should use site ID instead of site name when generating links'
```

**Comment by d-mendoza** [comment]
@yaniv-li I think I don't have access rights to make a PR.

```
ERROR: Permission to cloudinary/cloudinary_sfcc_pagedesigner.git denied to d-mendoza.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by d-mendoza** [comment]
@yaniv-li Can you provide some insight here?

**Comment by yaniv-li** [comment]
@d-mendoza you should branch out of the main branch make your fixes and then push that branch, and make PR from it.

**Comment by d-mendoza** [comment]
@yaniv-li That's what I did, let me try this again and see what happens

**Comment by d-mendoza** [comment]
@yaniv-li I tired to do it and I got this error:

```
ERROR: Permission to cloudinary/cloudinary_sfcc_pagedesigner.git denied to d-mendoza.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
