### ISSUE TITLE
Cartrdige name typo in Readme.md

### ISSUE THREAD

**Issue by ysazak** [cloudinary/cloudinary_sfcc_pagedesigner#34]
The site cartridge name mentioned in _Update the site cartridge path_ section should be _int_cloudinary_pd_ instead of  _int_cloudinary_pad_

https://github.com/cloudinary/cloudinary_sfcc_pagedesigner#update-the-site-cartridge-path

**Comment by MiskonceptioN** [comment]
Hi Yasar.

Thanks for bringing this to our attention. I've created a PR to address this which should be reviewed and merged soon.

Thanks,
-Danny Valentine
Developer Support Engineer
