### ISSUE TITLE
The responsive break points leave a large image that is too small.

### ISSUE THREAD

**Issue by amezick** [cloudinary/cloudinary_sfcc_pagedesigner#9]
In getBreackpoints() from cartridges/int_cloudinary_pd/cartridge/controllers/Brpoints.js  the max_width is too small.  Can this be configurable?  

I was going to extend the file but the use of local functions inside of a controller makes that difficult.  My SF Architect suggested I do a server.replace on the route and move the local functions into a helper method.

**Comment by naveenpras** [comment]
Based on discussions, we'll attempt to expose this through code initially.  We can think about exposing this through the UI later on.

**Comment by amezick** [comment]
That works for me.

**Comment by naveenpras** [comment]
Angus needs to set the upper limit for the breakpoint, e.g. say that we need to set the biggest breakpoint.

**Comment by naveenpras** [comment]
The example is:
Pick a image at 400x400
The srcsets start at 2000 px and so the image is scaled up.  

Check
function getBreackpoints(publicId) {
    var body = {
        timestamp: (Date.now() / 1000).toFixed(),
        public_id: publicId,
        type: 'upload',
        responsive_breakpoints: [
            {
                bytes_step: 20000,
                max_width: 1000,
                max_images: 20,
                min_width: 200
            }]
    };
    body.signature = utils.addSignatureToBody(body);
    body.responsive_breakpoints = utils.stringifyJson(body.responsive_breakpoints);
    body.api_key = currentSite.getCustomPreferenceValue('CloudinaryPageDesignerAPIkey');
    var r = utils.callService(body, 'image', 'explicit');
    if (r.ok) {
        var result = r.message;
        return getBreackpointsFromResponse(result);
    }
    return [1280, 768, 375];
}
